# Generated by Django 4.2.2 on 2023-06-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=1, verbose_name='Comment content'),
            preserve_default=False,
        ),
    ]
